version: '3.9'


services:
  # Database
  postgres:
    image: postgres:15
    volumes:
      - .data/db:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env/.env.dev
    # environment:
    #   - POSTGRES_PASSWORD: password 
    #   - POSTGRES_USER : hello
    #   - POSTGRES_DB: yourdb
    #   - POSTGRES_PORT: 5432
    networks:
      - postgres

  # db:
  #   image: mysql:8
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: yourdb
  #     MYSQL_PASSWORD: password
  #   networks:
  #     - mysql-phpmyadmin
  #     # - mysql-api

  # # phpmyadmin
  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - "8090:80"
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: password
  #   networks:
  #     - mysql-phpmyadmin

  # api
  # api:
  #   restart: always
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   ports:
  #     # - "3306:3306"
  #     - "8000:80"
  #   depends_on:
  #     - db
  #   networks:
  #     - mysql-api

networks:
  postgres:
  # mysql-phpmyadmin:
  # mysql-api:

volumes:
  db_data: