
name: Python Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Call webhook for deployment
      run: wget -qO- 'https://api.render.com/deploy/srv-cli8tet8td7s73btpr70?key=ayFmYq0A1A0'