name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]


jobs:

  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10.12"]
        poetry-version: ["1.7.0"]

    # runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: View poetry --help
        run: poetry --help

    # - name: Run tests with pytest
    #   run: |
    #     poetry run pytest
